# Ejemplos

POST http://localhost:3000/api/products HTTP/1.1
content-type: application/json

{ 
    "nombre": "Camiseta", 
    "precio": 200 ,
    "marca": "Gucci"
}

### 

POST http://localhost:3000/api/products HTTP/1.1
content-type: application/json

{ 
  "nombre": "Lampara", 
    "precio": 13 ,
    "marca": "Fury"
}

### 

GET http://localhost:3000/api/products HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/products/655fcafbbbe73a079034d6d4 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/products/655fcc35bbe73a079034d6d6 HTTP/1.1
content-type: application/json

{ 
   "nombre": "Armario", 
    "precio": 780 ,
    "marca": "Ikea"
}

###

DELETE http://localhost:3000/api/products/655fcc26bbe73a079034d6d5 HTTP/1.1
content-type: application/json


